### PR TITLE
add_tricks_section

### PR DESCRIPTION
**Pull request by iveksl2**

### CODE REVIEW

**Comment by iveksl2** [comment]
@peterhurford @robertzk are these fair statements? thx

**Comment by robertzk** [comment]
I just see a style change (boldening of the Q); is the diff accurate?

**Comment by peterhurford** [comment]
@iveksl2 @robertzk Looks like this is the commit with the questions https://github.com/iveksl2/r_py_mirror/pull/2/commits/b636954d543111204aaf1d007fb88341442cab21 but it got overwritten.

**Comment by iveksl2** [comment]
Sorry for the confusion. @robertzk @peterhurford if you don't like the style let me know as small things like aesthetics are important but I just meant the content with `dir` in python being the best equivalent to `ls` in R or if thats not really a fair statement. thx!

**Comment by peterhurford** [comment]
@iveksl2 Yep, that sounds pretty much right. There are slight differences I think with how `ls(obj)` and `dir(obj)` work (with `dir(obj)` being seemingly more useful).

**Comment by iveksl2** [comment]
@peterhurford would you expand on the small differences within PR, otherwise then good to merge?

**Comment by peterhurford** [comment]
@iveksl2 I expanded on it in https://github.com/iveksl2/r_py_mirror/pull/3, let me know if that's good and then LGTM :shipit: 👍

**Comment by iveksl2** [comment]
@peterhurford you da man w/ da 5 yr plan

**Pull request merged**
